sudo: true
services:
- docker
before_install:
- sudo sysctl -w vm.max_map_count=262144
- cp test/elasticsearch/elasticsearch.yml elasticsearch-docker/build/elasticsearch/
# copied from elasticsearch-docker/Makefile, run-es-single step
- docker pull ${BASEIMAGE}
install:
- docker-compose
    -f elasticsearch-docker/docker-compose.yml
    -f docker-compose.yml
    up -d --build
    elasticsearch1 fscrawler
- sleep 25 # wait 10 seconds for elasticsearch to boot + 10 seconds for fscrawler to complete a round
script:
- docker-compose 
    -f elasticsearch-docker/docker-compose.yml
    -f docker-compose.yml
    exec fscrawler
    cat /root/.fscrawler/myjob/_status.json > test/actual_status.json
- cat test/actual_status.json
- test `cat test/actual_status.json |jq '.indexed'` -eq 1
- docker-compose 
    -f elasticsearch-docker/docker-compose.yml
    -f docker-compose.yml
    logs fscrawler
after_script:
- docker-compose
    -f elasticsearch-docker/docker-compose.yml
    -f docker-compose.yml
    down

# Copied from elasticsearch-docker/Makefile
env:
  matrix:
    - FSCRAWLER_VER=2.1
    - FSCRAWLER_VER=2.2
  global:
    - ELASTIC_VERSION=5.1.2
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch
    - ES_JAVA_OPTS=""
    - VERSIONED_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    - ELASTIC_REGISTRY=docker.elastic.co
    - BASEIMAGE=${ELASTIC_REGISTRY}/elasticsearch/elasticsearch-alpine-base:latest
    - ES_NODE_COUNT=1 
addons:
  apt:
    packages:
      - jq
