services:
- docker
before_install:
- sysctl -w vm.max_map_count=262144
- git clone https://github.com/elastic/elasticsearch-docker
  && cd elasticsearch-docker
  && make run-es-single
- docker build -t fscrawler .
script:
- docker run -it --rm --name my-fscrawler 
  -v $PWD/data/:/data/fscrawler/files/:ro 
  -v $PWD/config:/data/fscrawler/home/:ro 
  fscrawler
