version: '2.1'
services:
  fscrawler:
    build:
      context: ${PWD}
    volumes:
    - ${PWD}/test/data/:/usr/share/fscrawler/data/:ro
    - ${PWD}/config/docker-compose:/usr/share/fscrawler/config-mount/docker-compose
    depends_on:
      elasticsearch1:
        condition: service_healthy
    command:
      - --trace
      - --config_dir
      - /usr/share/fscrawler/config
      - docker-compose
    networks:
      - esnet

  elasticsearch1:
    build:
      context: ${PWD}/elasticsearch-docker/build/elasticsearch
