version: '2'
services:
  fscrawler:
    build:
      context: ${PWD}
    volumes:
    - ${PWD}/test/data/:/usr/share/fscrawler/data/
    depends_on:
    - elasticsearch1

  elasticsearch1:
    build:
      context: ${PWD}/elasticsearch-docker/build/elasticsearch
