version: '2'
services:
  fscrawler:
    build:
      context: ${PWD}
      args:
        FSCRAWLER_VER: "${FSCRAWLER_VER}"
    volumes:
    - ${PWD}/test/data/:/data/fscrawler/files/:ro
    - ${PWD}/test/config:/data/fscrawler/home/:ro
    depends_on:
    - elasticsearch1
  elasticsearch1:
    build:
      context: ${PWD}/elasticsearch-docker/build/elasticsearch
